
spring:
  application:
    name: federatedlearning
  data:
    mongodb:
      host: localhost
      port: 27017
      database: fl


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/联邦学习
    username: root
    password: shujuku
mybatis:
  configuration:
    map-underscore-to-camel-case: true

    #开启驼峰命名和用下划线命名的自动转换
server:
  port: 8081


#logging:
#  level:
#    org:
#      springframework:
#        web: DEBUG
#    com:
#      example:
#        federatedlearning: DEBUG

logging:
  level:
    root: INFO
    org:
      springframework:
        web: DEBUG
        data:
          mongodb:
            core: DEBUG  # 更精确的MongoDB日志控制
    com:
      example:
        federatedlearning: DEBUG
    org.mongodb.driver: WARN

